2019-12-26 15:42:13,679 | ERROR | MainProcess-4984 | Textual SQL expression '' should be explicitly declared as text('')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=5, page_size=2, filters='', order_bys=['id'])
  File "H:\self\flask-template\components\bases.py", line 148, in list_pagination
    items = self.session.query(self.model_cls) \
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression '' should be explicitly declared as text('')
2019-12-26 15:51:33,780 | ERROR | MainProcess-7632 | Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=4, page_size=4, filters=['a'], order_bys=['id'])
  File "H:\self\flask-template\components\bases.py", line 148, in list_pagination
    items = self.session.query(self.model_cls) \
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 15:52:03,353 | ERROR | MainProcess-592 | (pymysql.err.InternalError) (1054, "Unknown column 'a' in 'where clause'")
[SQL: SELECT user.id AS user_id, user.create_time AS user_create_time, user.update_time AS user_update_time, user.is_deleted AS user_is_deleted, user.username AS user_username, user.password AS user_password, user.email AS user_email 
FROM user 
WHERE a ORDER BY user.id 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'param_1': 12, 'param_2': 4}]
(Background on this error at: http://sqlalche.me/e/2j85)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "E:\env\test\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "E:\env\test\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'a' in 'where clause'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 48, in get
    users = self.service.list_pagination(current_page=4, page_size=4, filters=[db.text('a')], order_bys=['id'])
  File "H:\self\flask-template\components\bases.py", line 148, in list_pagination
    items = self.session.query(self.model_cls) \
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3211, in all
    return list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "E:\env\test\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "E:\env\test\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'a' in 'where clause'")
[SQL: SELECT user.id AS user_id, user.create_time AS user_create_time, user.update_time AS user_update_time, user.is_deleted AS user_is_deleted, user.username AS user_username, user.password AS user_password, user.email AS user_email 
FROM user 
WHERE a ORDER BY user.id 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'param_1': 12, 'param_2': 4}]
(Background on this error at: http://sqlalche.me/e/2j85)
2019-12-26 15:53:00,210 | ERROR | MainProcess-11096 | Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=4, page_size=4, filters='a', order_bys=['id'])
  File "H:\self\flask-template\components\bases.py", line 148, in list_pagination
    items = self.session.query(self.model_cls) \
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 16:25:06,361 | ERROR | MainProcess-7144 | 'BaseQuery' object has no attribute 'msearsh'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 153, in list_pagination
    items = self.session.query(self.model_cls) \
AttributeError: 'BaseQuery' object has no attribute 'msearsh'
2019-12-26 16:28:50,655 | ERROR | MainProcess-3872 | object of type 'Query' has no len()
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 48, in get
    return self.success(data={'users': self.schema.dump(users, many=True), 'count': len(users)})
  File "H:\self\flask-template\components\pagination.py", line 35, in __len__
    return len(self.list)
TypeError: object of type 'Query' has no len()
2019-12-26 16:30:08,111 | ERROR | MainProcess-2892 | Textual SQL expression '5' should be explicitly declared as text('5')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='5', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 158, in list_pagination
    total = self.session.query(self.model_cls).filter(*filters).order_by(*order_bys).count()
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression '5' should be explicitly declared as text('5')
2019-12-26 16:30:42,416 | ERROR | MainProcess-10316 | 'list' object has no attribute 'split'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters=['5'], order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 153, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filters, fields=['username', 'email'])
  File "E:\env\test\lib\site-packages\flask_msearch\backends.py", line 180, in whoosh_search
    return self.msearch(m, query, fields, limit, or_)
  File "E:\env\test\lib\site-packages\flask_msearch\simple_backend.py", line 26, in msearch
    keywords = query.split(' ')
AttributeError: 'list' object has no attribute 'split'
2019-12-26 16:30:57,801 | ERROR | MainProcess-7532 | Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='a', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 158, in list_pagination
    total = self.session.query(self.model_cls).filter(*filters).order_by(*order_bys).count()
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 16:31:56,219 | ERROR | MainProcess-7440 | Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='a', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 158, in list_pagination
    total = self.session.query(self.model_cls).filter(*filters).order_by(*order_bys).count()
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 16:55:27,726 | ERROR | MainProcess-8220 | Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 776, in visit_textual_label_reference
    col = with_cols[element.element]
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 154, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filters) \
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3211, in all
    return list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1086, in _execute_clauseelement
    compiled_sql = elem.compile(
  File "<string>", line 1, in <lambda>
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 468, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 571, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 2138, in visit_select
    text = self._compose_select_body(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 2251, in _compose_select_body
    text += self.order_by_clause(select, **kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 2310, in order_by_clause
    order_by = select._order_by_clause._compiler_dispatch(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 979, in visit_clauselist
    text = sep.join(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 979, in <genexpr>
    text = sep.join(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 982, in <genexpr>
    c._compiler_dispatch(self, **kw) for c in clauselist.clauses
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 778, in visit_textual_label_reference
    elements._no_text_coercion(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 17:05:47,089 | ERROR | MainProcess-2656 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 161, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:06:40,781 | ERROR | MainProcess-4360 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 161, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:07:31,546 | ERROR | MainProcess-9800 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 161, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:08:34,611 | ERROR | MainProcess-9800 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 161, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:09:41,740 | ERROR | MainProcess-2064 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 161, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:10:13,649 | ERROR | MainProcess-3008 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 161, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:10:41,183 | ERROR | MainProcess-6700 | object of type 'Query' has no len()
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 156, in list_pagination
    print('*' * 200, len(items))
TypeError: object of type 'Query' has no len()
2019-12-26 17:11:27,574 | ERROR | MainProcess-10316 | 'SimpleSearch' object has no attribute 'mearch'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 152, in list_pagination
    items = search.mearch(self.model_cls, query=filters) \
  File "E:\env\test\lib\site-packages\flask_msearch\__init__.py", line 46, in __getattr__
    return getattr(self._backend, name)
AttributeError: 'SimpleSearch' object has no attribute 'mearch'
2019-12-26 17:11:59,058 | ERROR | MainProcess-7964 | object of type 'Query' has no len()
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 156, in list_pagination
    print('*' * 200, len(items))
TypeError: object of type 'Query' has no len()
2019-12-26 17:12:34,703 | ERROR | MainProcess-10076 | Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 776, in visit_textual_label_reference
    col = with_cols[element.element]
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 152, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filters) \
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3211, in all
    return list(self)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1086, in _execute_clauseelement
    compiled_sql = elem.compile(
  File "<string>", line 1, in <lambda>
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 468, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 571, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 2138, in visit_select
    text = self._compose_select_body(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 2251, in _compose_select_body
    text += self.order_by_clause(select, **kwargs)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 2310, in order_by_clause
    order_by = select._order_by_clause._compiler_dispatch(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 979, in visit_clauselist
    text = sep.join(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 979, in <genexpr>
    text = sep.join(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 982, in <genexpr>
    c._compiler_dispatch(self, **kw) for c in clauselist.clauses
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\compiler.py", line 778, in visit_textual_label_reference
    elements._no_text_coercion(
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 17:13:06,369 | ERROR | MainProcess-7848 | object of type 'Query' has no len()
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 157, in list_pagination
    print('*' * 200, len(items))
TypeError: object of type 'Query' has no len()
2019-12-26 17:13:27,085 | ERROR | MainProcess-3160 | object of type 'Query' has no len()
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 157, in list_pagination
    print('*' * 200, len(items))
TypeError: object of type 'Query' has no len()
2019-12-26 17:16:04,097 | ERROR | MainProcess-1152 | Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 146, in list_pagination
    items = self.session.query(self.model_cls) \
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 17:16:24,819 | ERROR | MainProcess-5204 | 'list' object has no attribute 'msearch'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 146, in list_pagination
    items = self.session.query(self.model_cls) \
AttributeError: 'list' object has no attribute 'msearch'
2019-12-26 17:18:53,484 | ERROR | MainProcess-7724 | Textual SQL expression 'a' should be explicitly declared as text('a')
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 146, in list_pagination
    items = self.session.query(self.model_cls) \
  File "<string>", line 2, in filter
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1789, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4556, in _expression_literal_as_text
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4565, in _literal_as
    return text_fallback(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4604, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'a' should be explicitly declared as text('a')
2019-12-26 17:19:09,321 | ERROR | MainProcess-5196 | 'list' object has no attribute 'msearch'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 146, in list_pagination
    items = self.session.query(self.model_cls) \
AttributeError: 'list' object has no attribute 'msearch'
2019-12-26 17:19:48,541 | ERROR | MainProcess-8356 | 'BaseQuery' object has no attribute 'msearch'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 146, in list_pagination
    items = self.session.query(self.model_cls) \
AttributeError: 'BaseQuery' object has no attribute 'msearch'
2019-12-26 17:23:08,945 | ERROR | MainProcess-6704 | 'Results' object has no attribute 'count'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 158, in list_pagination
    total = search.whoosh_search(self.model_cls, query=filters).count()
AttributeError: 'Results' object has no attribute 'count'
2019-12-26 17:23:47,136 | ERROR | MainProcess-4696 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 152, in list_pagination
    for item in items:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 17:29:02,137 | ERROR | MainProcess-7172 | SQL expression object expected, got object of type <class 'tuple'> instead
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 151, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filters) \
  File "<string>", line 2, in order_by
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 1850, in order_by
    criterion = self._adapt_col_list(criterion)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 308, in _adapt_col_list
    return [
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 310, in <listcomp>
    expression._literal_as_label_reference(o), True, True
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4536, in _literal_as_label_reference
    return _literal_as_text(element)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4579, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 4569, in _literal_as
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: SQL expression object expected, got object of type <class 'tuple'> instead
2019-12-26 17:29:53,596 | ERROR | MainProcess-6804 | Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 154, in list_pagination
    print(items.order_by('id'))
  File "<string>", line 2, in order_by
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 219, in generate
    assertion(self, fn.__name__)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 487, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
2019-12-26 17:30:18,271 | ERROR | MainProcess-8848 | 'list' object has no attribute 'order_by'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 155, in list_pagination
    print(items.order_by('id'))
AttributeError: 'list' object has no attribute 'order_by'
2019-12-26 17:30:32,758 | ERROR | MainProcess-628 | Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 154, in list_pagination
    print(items.order_by('id'))
  File "<string>", line 2, in order_by
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 219, in generate
    assertion(self, fn.__name__)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 487, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
2019-12-26 17:32:00,838 | ERROR | MainProcess-3236 | Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 155, in list_pagination
    print(items.order_by('id'))
  File "<string>", line 2, in order_by
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 219, in generate
    assertion(self, fn.__name__)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 487, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
2019-12-26 17:32:57,468 | ERROR | MainProcess-6788 | 'list' object has no attribute 'order_by'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 154, in list_pagination
    print(items.order_by('id'))
AttributeError: 'list' object has no attribute 'order_by'
2019-12-26 17:33:15,197 | ERROR | MainProcess-2288 | 'list' object has no attribute 'order_by'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa', order_bys=('id',))
  File "H:\self\flask-template\components\bases.py", line 155, in list_pagination
    print(items.order_by('id'))
AttributeError: 'list' object has no attribute 'order_by'
2019-12-26 17:34:32,689 | ERROR | MainProcess-6196 | Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=3, filters='aa')
  File "H:\self\flask-template\components\bases.py", line 151, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filters, limit=3) \
  File "<string>", line 2, in order_by
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\base.py", line 219, in generate
    assertion(self, fn.__name__)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 487, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
2019-12-26 17:43:12,830 | ERROR | MainProcess-4600 | object of type 'Query' has no len()
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 47, in get
    users = self.service.list_pagination(current_page=2, page_size=4, filters='aa')
  File "H:\self\flask-template\components\bases.py", line 155, in list_pagination
    print(len(items))
TypeError: object of type 'Query' has no len()
2019-12-26 17:57:23,742 | ERROR | MainProcess-1708 | 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    users = self.service.list_pagination(current_page=req_data.get('current_page'),
  File "H:\self\flask-template\components\bases.py", line 152, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filter) \
  File "E:\env\test\lib\site-packages\flask_msearch\backends.py", line 180, in whoosh_search
    return self.msearch(m, query, fields, limit, or_)
  File "E:\env\test\lib\site-packages\flask_msearch\simple_backend.py", line 26, in msearch
    keywords = query.split(' ')
AttributeError: 'NoneType' object has no attribute 'split'
2019-12-26 17:58:00,841 | ERROR | MainProcess-6148 | 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 53, in get
    users = self.service.list_pagination(current_page=req_data.get('current_page'),
  File "H:\self\flask-template\components\bases.py", line 152, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filter) \
  File "E:\env\test\lib\site-packages\flask_msearch\backends.py", line 180, in whoosh_search
    return self.msearch(m, query, fields, limit, or_)
  File "E:\env\test\lib\site-packages\flask_msearch\simple_backend.py", line 26, in msearch
    keywords = query.split(' ')
AttributeError: 'NoneType' object has no attribute 'split'
2019-12-26 17:59:53,251 | ERROR | MainProcess-2892 | 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 53, in get
    users = self.service.list_pagination(current_page=req_data.get('current_page'),
  File "H:\self\flask-template\components\bases.py", line 152, in list_pagination
    items = search.whoosh_search(self.model_cls, query=filter) \
  File "E:\env\test\lib\site-packages\flask_msearch\backends.py", line 180, in whoosh_search
    return self.msearch(m, query, fields, limit, or_)
  File "E:\env\test\lib\site-packages\flask_msearch\simple_backend.py", line 26, in msearch
    keywords = query.split(' ')
AttributeError: 'NoneType' object has no attribute 'split'
2019-12-26 19:04:31,001 | ERROR | MainProcess-12132 | 'Pagination' object has no attribute 'pop'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 53, in get
    pagination_users['users'] = self.schema.dump(pagination_users.pop('users'))
AttributeError: 'Pagination' object has no attribute 'pop'
2019-12-26 19:05:44,875 | ERROR | MainProcess-7784 | the JSON object must be str, bytes or bytearray, not Pagination
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    return json.loads(pagination)
  File "c:\program files\python\Lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Pagination
2019-12-26 19:05:58,487 | ERROR | MainProcess-32 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    return json.loads(str(pagination))
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:06:31,119 | ERROR | MainProcess-3388 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data)
  File "H:\self\flask-template\components\bases.py", line 171, in list_pagination
    return json.loads(str(pagination))
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:07:37,784 | ERROR | MainProcess-10904 | 'Pagination' object is not subscriptable
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    for p in pagination['list']:
TypeError: 'Pagination' object is not subscriptable
2019-12-26 19:08:11,167 | ERROR | MainProcess-11996 | the JSON object must be str, bytes or bytearray, not Pagination
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    for p in json.loads(pagination)['list']:
  File "c:\program files\python\Lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Pagination
2019-12-26 19:08:29,004 | ERROR | MainProcess-2968 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    for p in json.loads(str(pagination))['list']:
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:10:42,565 | ERROR | MainProcess-11612 | 'Pagination' object has no attribute 'pop'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 54, in get
    pagination_users['users'] = self.schema.dump(pagination_users.pop('users'))
AttributeError: 'Pagination' object has no attribute 'pop'
2019-12-26 19:11:33,516 | ERROR | MainProcess-11412 | 'Pagination' object has no attribute 'pop'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 54, in get
    pagination_users['users'] = self.schema.dump(pagination_users.pop('users'))
AttributeError: 'Pagination' object has no attribute 'pop'
2019-12-26 19:11:59,495 | ERROR | MainProcess-11576 | 'Pagination' object has no attribute 'pop'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 55, in get
    pagination_users['users'] = self.schema.dump(pagination_users.pop('users'))
AttributeError: 'Pagination' object has no attribute 'pop'
2019-12-26 19:13:18,546 | ERROR | MainProcess-10652 | 'Pagination' object has no attribute 'pop'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 55, in get
    pagination_users['users'] = self.schema.dump(pagination_users.pop('users'))
AttributeError: 'Pagination' object has no attribute 'pop'
2019-12-26 19:40:06,103 | ERROR | MainProcess-7520 | 'dict' object has no attribute 'list'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 169, in list_pagination
    pagination_info = json.loads(str(Pagination(current_page, page_size, total, items)))  # 获取分页状况信息
  File "H:\self\flask-template\components\pagination.py", line 41, in __str__
    d = self.__dict__.__delattr__('list')
AttributeError: 'dict' object has no attribute 'list'
2019-12-26 19:40:47,461 | ERROR | MainProcess-11896 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 169, in list_pagination
    pagination_info = json.loads(str(Pagination(current_page, page_size, total, items)))  # 获取分页状况信息
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:41:23,331 | ERROR | MainProcess-8704 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 169, in list_pagination
    pagination_info = json.loads(str(Pagination(current_page, page_size, total, items)))  # 获取分页状况信息
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:42:02,298 | ERROR | MainProcess-11400 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 169, in list_pagination
    print(json.loads(a))
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:42:20,536 | ERROR | MainProcess-2544 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    pagination_info = json.loads(str(Pagination(current_page, page_size, total, items)))  # 获取分页状况信息
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:42:40,370 | ERROR | MainProcess-4796 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    pagination_info = json.loads(str(Pagination(current_page, page_size, total, items)))  # 获取分页状况信息
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 19:43:09,121 | ERROR | MainProcess-10100 | Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 170, in list_pagination
    pagination_info = json.loads(str(Pagination(current_page, page_size, total, items)))  # 获取分页状况信息
  File "c:\program files\python\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2019-12-26 20:06:17,276 | ERROR | MainProcess-2056 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:07:47,755 | ERROR | MainProcess-6216 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:11:45,277 | ERROR | MainProcess-7560 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:12:15,448 | ERROR | MainProcess-5480 | 'ChineseTokenizer' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'ChineseTokenizer' object has no attribute 'translate'
2019-12-26 20:12:30,735 | ERROR | MainProcess-11416 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:17:06,371 | ERROR | MainProcess-11512 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:18:50,759 | ERROR | MainProcess-11592 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:20:19,697 | ERROR | MainProcess-11948 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:20:47,253 | ERROR | MainProcess-2288 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:21:24,746 | ERROR | MainProcess-12248 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:22:47,166 | ERROR | MainProcess-200 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 164, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:23:09,164 | ERROR | MainProcess-2616 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    print(len(list(items)))
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:23:46,421 | ERROR | MainProcess-5516 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 163, in list_pagination
    for item in items:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:25:01,834 | ERROR | MainProcess-2576 | type() takes 1 or 3 arguments
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 164, in list_pagination
    print(type(items, Iterable))
TypeError: type() takes 1 or 3 arguments
2019-12-26 20:25:49,980 | ERROR | MainProcess-11484 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 167, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:26:21,262 | ERROR | MainProcess-1404 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 166, in list_pagination
    for i in items:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
2019-12-26 20:29:08,425 | ERROR | MainProcess-2812 | ChineseTokenizer() takes no arguments
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 160, in list_pagination
    items = search.msearch(self.model_cls, query=filter) \
  File "E:\env\test\lib\site-packages\flask_msearch\simple_backend.py", line 24, in msearch
    keywords = self.analyzer(query)
TypeError: ChineseTokenizer() takes no arguments
2019-12-26 20:29:38,901 | ERROR | MainProcess-10156 | 'Token' object has no attribute 'translate'
Traceback (most recent call last):
  File "E:\env\test\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\test\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\env\test\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\env\test\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "H:\self\flask-template\apps\app\handlers.py", line 52, in get
    pagination_users = self.service.list_pagination(pagination_data, model_schema=self.schema)
  File "H:\self\flask-template\components\bases.py", line 164, in list_pagination
    if current_page == 1 and len(list(items)) < page_size:
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "E:\env\test\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "E:\env\test\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "E:\env\test\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "E:\env\test\lib\site-packages\pymysql\connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "E:\env\test\lib\site-packages\pymysql\converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Token' object has no attribute 'translate'
